# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 05:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=datetime.datetime(2018, 7, 29, 5, 33, 12, 509686))),
                ('token', models.CharField(default=b'7b0c3d7a-05c7-42c8-9f41-b43783b5a61a', max_length=128)),
                ('logout_time', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_models.User'),
        ),
    ]
